# Generated by Django 3.2.9 on 2021-11-15 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreateModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_id', models.IntegerField(verbose_name='Номер подразделения')),
                ('second_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=100, verbose_name='Отчество')),
                ('position', models.CharField(max_length=500, verbose_name='Должность')),
                ('db_id', models.IntegerField(verbose_name='Уникальный индификатор')),
                ('full_name', models.CharField(max_length=300, verbose_name='ФИО')),
            ],
        ),
    ]
