# Generated by Django 3.2.9 on 2021-11-15 05:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreatemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создано'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usercreatemodel',
            name='is_created',
            field=models.BooleanField(default=False, verbose_name='Пользователь создан'),
        ),
        migrations.AddField(
            model_name='usercreatemodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
