# Generated by Django 3.2.9 on 2021-11-15 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_user', '0002_auto_20211115_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercreatemodel',
            name='personal_number',
            field=models.IntegerField(default=3, verbose_name='Табельный номер'),
            preserve_default=False,
        ),
    ]
