version: "3.7"

services:
  web:
    image: vdobrokhotov/web-adminsite:v1.0
    volumes:
      - .:/usr/src/adminsite
    entrypoint: ./entrypoint.sh
    depends_on:
      - db_post
    ports:
      - "8000:8000"

  db_post:
    image: postgres:14.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=dctlkzdthatq

  nginx:
    image: vdobrokhotov/nginx-adminsite:v1.0
    volumes:
      - ./static_root:/usr/src/adminsite/static
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:


